Repository cse110-fa21-group30/cse110-fa21-group30, pull requests merged in 2021-11, with the labels that each got.

#19 Pitch
  specs/interface/highfidelity/MacBook Pro - 1.png
  specs/interface/highfidelity/MacBook Pro - 2.png
  specs/interface/highfidelity/MacBook Pro - 3.png
  specs/interface/highfidelity/MacBook Pro - 4.png
  specs/pitch/Group30_StartingPitch.pdf
Labels: documentation, meeting/note

#20 Create 110121-pitch.md
  admin/meetings/110121-pitch.md
Labels: meeting/note

#34 feat: add recipe card
  source/assets/components/RecipeCard.js
  source/assets/images/default.png
  source/assets/scripts/index.js
  source/index.html
  source/styles.css
Labels: enhancement

#46 Update phase1.md
  admin/cipipeline/phase1.md
Labels: documentation

#69 Recipe Add Page (HTML + CSS + JS)
  source/assets/images/Easy1.svg
  source/assets/images/Hard3.svg
  source/assets/images/Medium2.svg
  source/assets/images/VeryHard4.svg
  source/assets/scripts/recipe-add.js
  source/assets/styles/recipe-add.css
  source/recipe-add.html
Labels: enhancement, help wanted

#68 Add recipe detail page test
  tests/e2e/recipe-detailE2E.test.js
Labels: enhancement

#70 Added AddRecipe to Nav Bar
  source/assets/scripts/index.js
  source/assets/scripts/recipe-add.js
  source/assets/scripts/recipe-detail.js
  source/assets/scripts/recipe-searchPage.js
  source/assets/scripts/setting.js
Labels: enhancement

#71 update codacy include Github code scanning
  .github/workflows/codacy-analysis.yml
Labels: enhancement
